# k8s/delivery-service/mysql-delivery-init-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-delivery-init-scripts
  namespace: uberx-delivery
data:
  init_delivery.sql: |
    CREATE DATABASE IF NOT EXISTS delivery_service;
    USE delivery_service;

    CREATE TABLE IF NOT EXISTS riders (
        id VARCHAR(50) PRIMARY KEY,
        user_id VARCHAR(50) NOT NULL,
        name VARCHAR(100) NOT NULL,
        phone VARCHAR(20),
        license_number VARCHAR(50),
        vehicle_type ENUM('MOTORCYCLE', 'CAR', 'BICYCLE') DEFAULT 'MOTORCYCLE',
        vehicle_plate VARCHAR(20),
        is_active BOOLEAN DEFAULT TRUE,
        current_status ENUM('AVAILABLE', 'BUSY', 'OFFLINE') DEFAULT 'AVAILABLE',
        latitude DOUBLE,
        longitude DOUBLE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS trips (
        id VARCHAR(50) PRIMARY KEY,
        order_id VARCHAR(50) NOT NULL,
        rider_id VARCHAR(50),
        status ENUM('ASSIGNED', 'ACCEPTED', 'ARRIVED_AT_RESTAURANT', 'PICKED_UP', 'IN_TRANSIT', 'ARRIVED', 'COMPLETED', 'CANCELLED', 'PREPARING') DEFAULT 'ASSIGNED',
        pickup_location JSON,
        delivery_location JSON,
        pickup_time TIMESTAMP NULL,
        delivery_time TIMESTAMP NULL,
        estimated_arrival_time TIMESTAMP NULL,
        distance_km DECIMAL(10, 2),
        duration_minutes INT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (rider_id) REFERENCES riders(id) ON DELETE SET NULL
    );

    CREATE TABLE IF NOT EXISTS trip_status_history (
        id VARCHAR(50) PRIMARY KEY,
        trip_id VARCHAR(50) NOT NULL,
        status VARCHAR(50) NOT NULL,
        timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        notes TEXT,
        latitude DOUBLE,
        longitude DOUBLE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE
    );

    -- Add indexes
    CREATE INDEX idx_rider_status ON riders(current_status);
    CREATE INDEX idx_rider_location ON riders(latitude, longitude);
    CREATE INDEX idx_trip_status ON trips(status);
    CREATE INDEX idx_trip_rider ON trips(rider_id);
    CREATE INDEX idx_trip_order ON trips(order_id);
    CREATE INDEX idx_trip_history_trip ON trip_status_history(trip_id);
    CREATE INDEX idx_trip_history_status ON trip_status_history(status);

    -- Insert delivery riders
    INSERT INTO riders (id, user_id, name, phone, license_number, vehicle_type, vehicle_plate, is_active, current_status, latitude, longitude, created_at, updated_at)
    VALUES
      ('rider_001', '5', 'Delivery Driver', '1231231234', 'DL1234567', 'MOTORCYCLE', 'AB123CD', true, 'AVAILABLE', 37.7749, -122.4194, NOW(), NOW()),
      ('rider_002', '6', 'Jane Rider', '9879879876', 'DL7654321', 'CAR', 'XY789ZW', true, 'AVAILABLE', 37.7833, -122.4167, NOW(), NOW()),
      ('rider_003', '7', 'Sam Speedy', '5675675678', 'DL9876543', 'BICYCLE', NULL, false, 'OFFLINE', 37.7694, -122.4862, NOW(), NOW());

    -- Insert delivery trips
    INSERT INTO trips (id, order_id, rider_id, status, pickup_location, delivery_location, pickup_time, delivery_time, estimated_arrival_time, distance_km, duration_minutes, created_at, updated_at)
    VALUES
      -- Completed deliveries
      ('trip_001', '101', 'rider_001', 'COMPLETED', 
       '{"lat": 37.7749, "lng": -122.4194, "address": "Tasty Bites, 123 Food St, Cuisine City"}', 
       '{"lat": 37.7833, "lng": -122.4167, "address": "123 Main St, City"}',
       DATE_SUB(NOW(), INTERVAL 10 DAY), 
       DATE_SUB(NOW(), INTERVAL 10 DAY), 
       DATE_SUB(NOW(), INTERVAL 10 DAY),
       3.5, 15, 
       DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
       
      ('trip_002', '102', 'rider_002', 'COMPLETED', 
       '{"lat": 37.7694, "lng": -122.4862, "address": "Spice Garden, 456 Spice Ave, Flavor Town"}', 
       '{"lat": 37.7879, "lng": -122.4074, "address": "456 Elm St, Town"}',
       DATE_SUB(NOW(), INTERVAL 5 DAY), 
       DATE_SUB(NOW(), INTERVAL 5 DAY), 
       DATE_SUB(NOW(), INTERVAL 5 DAY),
       4.8, 22, 
       DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
       
      ('trip_003', '103', 'rider_001', 'COMPLETED', 
       '{"lat": 37.7694, "lng": -122.4074, "address": "Burger Palace, 789 Burger Blvd, Meal City"}', 
       '{"lat": 37.7833, "lng": -122.4167, "address": "123 Main St, City"}',
       DATE_SUB(NOW(), INTERVAL 2 DAY), 
       DATE_SUB(NOW(), INTERVAL 2 DAY), 
       DATE_SUB(NOW(), INTERVAL 2 DAY),
       2.9, 12, 
       DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),

      -- Ongoing delivery  
      ('trip_004', '105', 'rider_002', 'PREPARING', 
       '{"lat": 37.7749, "lng": -122.4194, "address": "Tasty Bites, 123 Food St, Cuisine City"}', 
       '{"lat": 37.7833, "lng": -122.4167, "address": "123 Main St, City"}',
       NULL, 
       NULL, 
       DATE_ADD(NOW(), INTERVAL 20 MINUTE),
       3.5, 15, 
       DATE_SUB(NOW(), INTERVAL 30 MINUTE), DATE_SUB(NOW(), INTERVAL 30 MINUTE));

    -- Trip status history
    INSERT INTO trip_status_history (id, trip_id, status, timestamp, notes, latitude, longitude, created_at, updated_at)
    VALUES
      -- Trip 1 history
      ('triphist_001', 'trip_001', 'ASSIGNED', DATE_SUB(NOW(), INTERVAL 10 DAY), 'Rider assigned to trip', 37.7749, -122.4194, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
      ('triphist_002', 'trip_001', 'ACCEPTED', DATE_SUB(NOW(), INTERVAL 10 DAY), 'Rider accepted trip', 37.7749, -122.4194, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
      ('triphist_003', 'trip_001', 'ARRIVED_AT_RESTAURANT', DATE_SUB(NOW(), INTERVAL 10 DAY), 'Rider arrived at restaurant', 37.7749, -122.4194, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
      ('triphist_004', 'trip_001', 'PICKED_UP', DATE_SUB(NOW(), INTERVAL 10 DAY), 'Order picked up', 37.7749, -122.4194, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
      ('triphist_005', 'trip_001', 'COMPLETED', DATE_SUB(NOW(), INTERVAL 10 DAY), 'Order delivered', 37.7833, -122.4167, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
      
      -- Trip 2 history
      ('triphist_006', 'trip_002', 'ASSIGNED', DATE_SUB(NOW(), INTERVAL 5 DAY), 'Rider assigned to trip', 37.7694, -122.4862, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
      ('triphist_007', 'trip_002', 'ACCEPTED', DATE_SUB(NOW(), INTERVAL 5 DAY), 'Rider accepted trip', 37.7694, -122.4862, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
      ('triphist_008', 'trip_002', 'ARRIVED_AT_RESTAURANT', DATE_SUB(NOW(), INTERVAL 5 DAY), 'Rider arrived at restaurant', 37.7694, -122.4862, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
      ('triphist_009', 'trip_002', 'PICKED_UP', DATE_SUB(NOW(), INTERVAL 5 DAY), 'Order picked up', 37.7694, -122.4862, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
      ('triphist_010', 'trip_002', 'COMPLETED', DATE_SUB(NOW(), INTERVAL 5 DAY), 'Order delivered', 37.7879, -122.4074, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
      
      -- Trip 3 history
      ('triphist_011', 'trip_003', 'ASSIGNED', DATE_SUB(NOW(), INTERVAL 2 DAY), 'Rider assigned to trip', 37.7694, -122.4074, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
      ('triphist_012', 'trip_003', 'ACCEPTED', DATE_SUB(NOW(), INTERVAL 2 DAY), 'Rider accepted trip', 37.7694, -122.4074, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
      ('triphist_013', 'trip_003', 'ARRIVED_AT_RESTAURANT', DATE_SUB(NOW(), INTERVAL 2 DAY), 'Rider arrived at restaurant', 37.7694, -122.4074, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
      ('triphist_014', 'trip_003', 'PICKED_UP', DATE_SUB(NOW(), INTERVAL 2 DAY), 'Order picked up', 37.7694, -122.4074, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
      ('triphist_015', 'trip_003', 'COMPLETED', DATE_SUB(NOW(), INTERVAL 2 DAY), 'Order delivered', 37.7833, -122.4167, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
      
      -- Trip 4 history (in progress)
      ('triphist_016', 'trip_004', 'ASSIGNED', DATE_SUB(NOW(), INTERVAL 30 MINUTE), 'Rider assigned to trip', 37.7749, -122.4194, DATE_SUB(NOW(), INTERVAL 30 MINUTE), DATE_SUB(NOW(), INTERVAL 30 MINUTE)),
      ('triphist_017', 'trip_004', 'ACCEPTED', DATE_SUB(NOW(), INTERVAL 25 MINUTE), 'Rider accepted trip', 37.7749, -122.4194, DATE_SUB(NOW(), INTERVAL 25 MINUTE), DATE_SUB(NOW(), INTERVAL 25 MINUTE)),
      ('triphist_018', 'trip_004', 'PREPARING', DATE_SUB(NOW(), INTERVAL 20 MINUTE), 'Waiting for order preparation', 37.7749, -122.4194, DATE_SUB(NOW(), INTERVAL 20 MINUTE), DATE_SUB(NOW(), INTERVAL 20 MINUTE));
