# k8s/uberx-restaurant/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: uberx-restaurant # <--- Correct namespace
  labels:
    app: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: thusalapi/restaurant-service:latest
        ports:
        - containerPort: 4001
        env:
        - name: NATS_URL
          value: "nats://nats.uberx-nats.svc.cluster.local:4222"    
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3004"
        - name: DB_HOST
          # Connect to DB service in the same namespace
          value: "mysql-restaurant" # <--- UPDATED HOST
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              # Secret is in the same namespace
              name: mysql-restaurant-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              # Secret is in the same namespace
              name: mysql-restaurant-credentials
              key: password
        - name: DB_NAME
          value: "restaurant_db"
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: access-token-secret
        # ... resources, probes ...
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5