apiVersion: v1
kind: Secret
metadata:
  name: mysql-restaurant-credentials
  namespace: uberx-restaurant  # Create the secret in restaurant namespace
type: Opaque
data:
  # Same values as the original secret
  root-password: Um9vdFBhc3MxMjM=
  username: b3JkZXJfdXNlcg==
  password: T3JkZXJQYXNzNDU2