# k8s/order-service/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: promotion-service
  namespace: uberx-promotion # <--- UPDATED NAMESPACE
spec:
  selector:
    app: promotion-service
  ports:
  - port: 5005
    targetPort: 5005
  type: ClusterIP