# k8s/uberx-db/mysql-auth-init-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-auth-init-scripts # ConfigMap holding init SQL for Auth DB
  namespace: uberx-auth
data:
  init_auth.sql: | # Script filename executed by mysql entrypoint
    CREATE DATABASE IF NOT EXISTS auth_db;
    USE auth_db;

    CREATE TABLE IF NOT EXISTS users (
        id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(100) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        fullName VARCHAR(50),
        role VARCHAR(20) DEFAULT 'customer',
        address VARCHAR(255),
        phone VARCHAR(20),
        vehicleREG VARCHAR(20),
        earning DECIMAL(10, 2) DEFAULT 0.00,
        location VARCHAR(255),
        is_active BOOLEAN DEFAULT TRUE,
        is_verified BOOLEAN DEFAULT FALSE,
        is_available BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS refresh_tokens (
        id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        userId INT UNSIGNED NOT NULL,
        token VARCHAR(500), # Raw token (consider if needed)
        token_hash VARCHAR(255) NOT NULL, # Hashed token for lookups
        expires_at TIMESTAMP NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        is_revoked BOOLEAN DEFAULT FALSE,
        UNIQUE KEY unique_token (token_hash),
        FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
    );
    
    # Insert initial user data
    INSERT INTO users (id, email, password, fullName, role, address, phone, is_active, is_verified, created_at, updated_at)
    VALUES 
      ('1', 'john@example.com', '$2a$10$XOPPbS.3Z/UVl0F9Pb1W4OJE7RwrFEIEYUy3FYGmWzKIPU9PKZ6lm', 'John Doe', 'customer', '123 Main St, City', '1234567890', true, true, NOW(), NOW()),
      ('2', 'jane@example.com', '$2a$10$XOPPbS.3Z/UVl0F9Pb1W4OJE7RwrFEIEYUy3FYGmWzKIPU9PKZ6lm', 'Jane Smith', 'customer', '456 Elm St, Town', '0987654321', true, true, NOW(), NOW()),
      ('3', 'admin@kamu.com', '$2a$10$XOPPbS.3Z/UVl0F9Pb1W4OJE7RwrFEIEYUy3FYGmWzKIPU9PKZ6lm', 'Admin User', 'admin', 'KAMU HQ, Business District', '1122334455', true, true, NOW(), NOW()),
      ('4', 'manager@restaurant.com', '$2a$10$XOPPbS.3Z/UVl0F9Pb1W4OJE7RwrFEIEYUy3FYGmWzKIPU9PKZ6lm', 'Restaurant Manager', 'restaurant', 'Restaurant A, Food Street', '5566778899', true, true, NOW(), NOW()),
      ('5', 'driver@kamu.com', '$2a$10$XOPPbS.3Z/UVl0F9Pb1W4OJE7RwrFEIEYUy3FYGmWzKIPU9PKZ6lm', 'Delivery Driver', 'driver', '789 Drive Way, City', '1231231234', true, true, NOW(), NOW())
    ON DUPLICATE KEY UPDATE
      updated_at = NOW();

    # Note: All passwords are 'password123' encrypted with bcrypt