name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Images to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Required for pushing to GitHub Container Registry

    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ghcr.io/${{ github.repository_owner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push auth-service
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          file: ./auth-service/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/auth-service:latest

      - name: Build and push order-service
        uses: docker/build-push-action@v5
        with:
          context: ./order-service
          file: ./order-service/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/order-service:latest

      - name: Build and push delivery-service
        uses: docker/build-push-action@v5
        with:
          context: ./delivery-service
          file: ./delivery-service/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/delivery-service:latest

      - name: Build and push payment-service
        uses: docker/build-push-action@v5
        with:
          context: ./payment-service
          file: ./payment-service/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/payment-service:latest

      - name: Build and push restaurant-service
        uses: docker/build-push-action@v5
        with:
          context: ./restaurant-service
          file: ./restaurant-service/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/restaurant-service:latest

      - name: Build and push nginx
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ env.IMAGE_PREFIX }}/nginx:latest
